from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class ResearchHypothesis:
    """
    A testable financial hypothesis generated by VFIA.

    A hypothesis is not automatically a trading strategy.
    """

    hypothesis_id: str
    statement: str

    created_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    assumptions: list[str] = field(default_factory=list)
    evidence: list[dict[str, Any]] = field(default_factory=list)
    proposed_tests: list[str] = field(default_factory=list)

    status: str = "proposed"
